WINDOW_SIZES = [60]
WINDOW_STEP_SIZES = [4]
MAPPERS = ["umap"]
N_NEIGHBORS = [2, 5, 10, 15, 20, 25, 30, 50, 100]
MIN_DIST = [0.01, 0.03, 0.1, 0.02, 0.3, 0.5, 0.7, 0.9]

wildcard_constraints:
    window_size=r"\d+",
    window_step_size=r"\d+"

rule all_window_sets:
    input:
        expand(
            "results/{mapper}/n_neighbors_{n_neighbors}/min_dist_{min_dist}/{window_size}/{window_step_size}/output.pdf",
            window_size=WINDOW_SIZES,
            window_step_size=WINDOW_STEP_SIZES,
            mapper=MAPPERS,
            n_neighbors=N_NEIGHBORS,
            min_dist=MIN_DIST,
        )

rule broken_window_set_umap:
    input:
        script="workflow/scripts/make_umap.py",
        fv="feature_vectors/{window_size}/{window_step_size}/feature_vecs.npy"
    output:
        "results/{mapper}/n_neighbors_{n_neighbors}/min_dist_{min_dist}/{window_size}/{window_step_size}/output.pdf"
    threads: 16
    resources:
        nodes=1,
        mem_str="256gb",
        runtime=28800
    shell:
        "OMP_NUM_THREADS={threads} workflow/envs/venv/bin/python {input.script} --window-size {wildcards.window_size} --window-step-size {wildcards.window_step_size} --feature-vecs-path {input.fv} --output-file {output} --mapper {wildcards.mapper} --neighbors {wildcards.n_neighbors} --min-dist {wildcards.min_dist}"

rule broken_window_set_fv:
    input:
        script="workflow/scripts/make_feature_vecs.py"
    output:
        protected("feature_vectors/{window_size}/{window_step_size}/feature_vecs.npy")
    threads: 32
    resources:
        nodes=1,
        mem_str="512gb",
        runtime=28800
    shell:
        "OMP_NUM_THREADS={threads} workflow/envs/venv/bin/python {input.script} --window-size {wildcards.window_size} --window-step-size {wildcards.window_step_size} --output-file {output}"
