WINDOW_SIZES = [100]
WINDOW_STEP_SIZES = [5, 10, 20, 30, 40, 50]

rule all_window_sets:
    input:
        expand(
            "results/{window_size}/{window_step_size}/output.pdf",
            window_size=WINDOW_SIZES,
            window_step_size=WINDOW_STEP_SIZES
        )

rule window_set:
    input:
        script="workflow/scripts/run.py"
    output:
        "results/{window_size}/{window_step_size}/output.pdf"
    threads: 32
    resources:
        nodes=4,
        mem_str="4tb",
        runtime=14400
    shell:
        "workflow/envs/venv/bin/python {input.script} --window-size {wildcards.window_size} --window-step-size {wildcards.window_step_size}"
