WINDOW_SIZES = [62]
WINDOW_STEP_SIZES = [10]
MAPPERS = ["umap"]
N_NEIGHBORS = [15]
MIN_DIST = [0.1]
INCLUDE_PROBABLY_WRONG_CODE = [0, 1]
NO_NORMALIZE = [0, 1]


wildcard_constraints:
    window_size=r"\d+",
    window_step_size=r"\d+"

rule all_window_sets:
    input:
        expand(
            "results/{mapper}/ipwc_{ipwc}/no_normalize_{no_normalize}/n_neighbors_{n_neighbors}/min_dist_{min_dist}/{window_size}/{window_step_size}/output.pdf",
            window_size=WINDOW_SIZES,
            window_step_size=WINDOW_STEP_SIZES,
            mapper=MAPPERS,
            n_neighbors=N_NEIGHBORS,
            min_dist=MIN_DIST,
            ipwc=INCLUDE_PROBABLY_WRONG_CODE,
            no_normalize=NO_NORMALIZE,
        )

rule broken_window_set_umap:
    input:
        script="workflow/scripts/make_umap.py",
        fv="feature_vectors/ipwc_{ipwc}/no_normalize_{no_normalize}/{window_size}/{window_step_size}/feature_vecs.npy"
    output:
        "results/{mapper}/ipwc_{ipwc}/no_normalize_{no_normalize}/n_neighbors_{n_neighbors}/min_dist_{min_dist}/{window_size}/{window_step_size}/output.pdf"
    threads: 16
    resources:
        nodes=1,
        mem_str="256gb",
        runtime=28800
    shell:
        "OMP_NUM_THREADS={threads} workflow/envs/venv/bin/python {input.script} --window-size {wildcards.window_size} --window-step-size {wildcards.window_step_size} --feature-vecs-path {input.fv} --output-file {output} --mapper {wildcards.mapper} --neighbors {wildcards.n_neighbors} --min-dist {wildcards.min_dist} --include-probably-wrong-code {wildcards.ipwc} --no-normalize {wildcards.no_normalize}"

rule broken_window_set_fv:
    input:
        script="workflow/scripts/make_feature_vecs.py"
    output:
        protected("feature_vectors/ipwc_{ipwc}/no_normalize_{no_normalize}/{window_size}/{window_step_size}/feature_vecs.npy")
    threads: 32
    resources:
        nodes=1,
        mem_str="512gb",
        runtime=28800
    shell:
        "OMP_NUM_THREADS={threads} workflow/envs/venv/bin/python {input.script} --window-size {wildcards.window_size} --window-step-size {wildcards.window_step_size} --output-file {output} --include-probably-wrong-code {wildcards.ipwc} --no-normalize {wildcards.no_normalize}"
