WINDOW_SIZES = [65]
WINDOW_STEPSIZES = [10]
TTCFS_I = [0]
TTCFS_J = [0]
N_NEIGHBORS = [2, 5, 10, 15, 20, 50, 100]
MIN_DIST = [0.01, 0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0]



rule all:
    input:
        expand(
            "plots/n_neighbors_{n_neighbors}/min_dist_{min_dist}/window_size_{window_size}/window_stepsize_{window_stepsize}",
            n_neighbors=N_NEIGHBORS,
            min_dist=MIN_DIST,
            window_size=WINDOW_SIZES,
            window_stepsize=WINDOW_STEPSIZES
        )

rule make_plots:
    input:
        script="workflow/scripts/make_plots.py",
        results="results/n_neighbors_{n_neighbors}/min_dist_{min_dist}/window_size_{window_size}/window_stepsize_{window_stepsize}/results.pkl"
    output:
        directory("plots/n_neighbors_{n_neighbors}/min_dist_{min_dist}/window_size_{window_size}/window_stepsize_{window_stepsize}")
    threads: 1
    resources:
        nodes=1,
        mem_str="16gb",
        runtime=600,
    shell:
        "mkdir -p {output} && workflow/envs/venv/bin/python {input.script} --results_path {input.results} --output-dir {output} --extension .pdf --ttcfs_i {TTCFS_I} --ttcfs_j {TTCFS_J}"

rule single:
    input:
        script="workflow/scripts/replicate_umap.py",
        data="../data"
    output:
        protected("results/n_neighbors_{n_neighbors}/min_dist_{min_dist}/window_size_{window_size}/window_stepsize_{window_stepsize}/results.pkl")
    threads: 16
    resources:
        nodes=1,
        mem_str="256gb",
        runtime=28800
    shell:
        "module load cuda; module load gcc; \
         NUMBA_NUM_THREADS={threads} \
         MKL_NUM_THREADS={threads} \
         OMP_NUM_THREADS={threads} \
         NUMBA_THREADING_LAYER=workqueue \
         UMAP_SKYRMION_DATA={input.data} \
         workflow/envs/venv/bin/python {input.script} --window-length {wildcards.window_size} --window-stepsize {wildcards.window_stepsize} --recorder-path {output} --n_neighbors {wildcards.n_neighbors} --min_dist {wildcards.min_dist}"
